Sprint 2
Replicatus/simple-chat pull request #17
Opened 2022-09-10 13:32 UTC by Replicatus

2022-09-10 23:23 UTC, agadoev requested changes
Привет, спасибо за работу)
Все задания выполнены, однако еще есть над чем поработать. В основном нужно порефакторить типы, но так же есть комментарии и по обычному JS  коду. Попробуй испраить эти моменты и двинемся дальше :)

2022-09-10 23:23 UTC, agadoev commented on src/consts.ts
> +            },
По хорошему функция-валидатор должна возвращать boolean, а не boolean или строку. Текст ошибки - это ответственность компонента, который рендерит шаблон. Текст ошибки должен создаваться в компоненте в зависимости от результата функции валидатора

2022-09-10 23:23 UTC, agadoev commented on src/consts.ts
> +]
```suggestion
    (v: string) => !!v || 'Обязательное поле',
    (v: string) => v.length >= 8 || 'Минимальное число символов 8',
    (v: string) => v.length <= 40 || 'Максимальное число символов 40',
    (v: string) => {
        const pattern = regularExpressions.password
        return pattern.test(v) || 'Неверно указан пароль'
    },
]
```

Я бы сделал вот так

2022-09-10 23:23 UTC, agadoev commented on src/pages/Login/index.ts
> +                        })
не имеет смысла использовать await вместе с .then(). Нужно оставить что-то одно

2022-09-10 23:23 UTC, agadoev commented on src/types.ts
> +    disabled?: string | boolean;
тут лучше оставить только boolean

2022-09-10 23:23 UTC, agadoev commented on src/types.ts
> +    value?: string | number | null | undefined;
Для таких типов удобно написать вспомогательный тип
```
type Nullable<T> = T | null | undefined
```

2022-09-11 18:44 UTC, Replicatus commented on src/pages/Login/index.ts
> +                        })
а как тогда сделать, ведь он промисы делает потом, а в функции он уже пробежал до ретурна где проверяется валидация

2022-09-11 18:45 UTC, Replicatus commented on src/consts.ts
> +            },
Видел реализацию валидации в vuetify && vuelidate решил сделать так же, какие минусы может такое решение дает?

2022-09-11 21:29 UTC, agadoev commented on src/consts.ts
> +            },
Если будешь сам реализовывать что-то по типу vuelidate, то из минусов то, что много времени придется потратить на реализацию, зато потом пользоваться будет удобно

2022-09-11 21:29 UTC, agadoev approved these changes
Привет, спасибо за правки, раобту принимаю

2022-09-11 21:53 UTC, merged