Sprint 3
Replicatus/simple-chat pull request #22
Opened 2022-09-25 19:33 UTC by Replicatus

Не все сделано по чек листу, а именно нет нормального удаление и добавления в чат пользователей и отправка сообщений между ними

2022-09-26 15:41 UTC, podlovchenko requested changes
Привет)

Сейчас при запуске проекта локально `Cannot GET /`
Нужно добавить в server.js отправку файла
```
app.use('*', (req, res) => {
	res.status(200).sendFile(__dirname + '/dist/index.html')
})
```

На нетлифае при обновлении страницы `Page not found`
Необходимо настроить редиректы в netlify.toml

2022-09-26 15:41 UTC, podlovchenko commented on src/api/AuthAPI.ts
> +    return this.http.post('/signin', {data: data});
```suggestion
    return this.http.post('/signin', {data});
```

2022-09-26 15:41 UTC, podlovchenko commented on src/api/AuthAPI.ts
> +    return this.http.post('/signup', {data: data});
Необходимо описать для всех методов тип возвращаемого значения

2022-09-26 15:41 UTC, podlovchenko commented on src/assets/styles/classes.sass
> +  display: flex !important
Использования !important не является хорошей практикой, лучше обойтись без него или повышать специфичность

2022-09-26 15:41 UTC, podlovchenko commented on src/assets/styles/components/avatar.sass
> +    //background-position: center center
Закомментированный код лучше не оставлять в проекте

2022-09-26 15:41 UTC, podlovchenko commented on src/components/avatar/index.ts
> +                    this.element.style.backgroundImage = `url(${imageUrl ? imageUrl :  props.url})`;
Можно использовать сокращенную форму
```suggestion
                    this.element.style.backgroundImage = `url(${imageUrl ??  props.url})`;
```

2022-10-12 07:38 UTC, podlovchenko requested changes

2022-10-12 07:38 UTC, podlovchenko commented on src/server.js
> +  res.status(200).sendFile(`${__dirname}/dist/index.html`);
Страница не отдается
Сейчас путь получается src/dist/index.html, а должен dist/index.html

2022-10-12 07:38 UTC, podlovchenko commented on src/server.js
>  const PORT = 3000;
Часто требуется возможность получить порт снаружи скрипта, не изменяя код, это можно сделать через переменное окружение:
process.env.PORT || PORT;
https://nodejs.org/dist/latest-v8.x/docs/api/process.html

2022-10-12 07:55 UTC, Replicatus commented on src/server.js
> +  res.status(200).sendFile(`${__dirname}/dist/index.html`);
Если честно не совсем понимаю, по ссылке из нетлифая все работает, где можно посмотреть эту ошибку?

2022-10-12 07:56 UTC, Replicatus commented on src/server.js
>  const PORT = 3000;
Имеется ввиду это ?
```
app.listen(process.env.PORT || PORT, () => {})
```

2022-10-12 14:37 UTC, podlovchenko commented on src/server.js
>  const PORT = 3000;
Да

2022-10-12 14:41 UTC, podlovchenko commented on src/server.js
> +  res.status(200).sendFile(`${__dirname}/dist/index.html`);
При запуске npm run start локально, npm run dev  работает
Сейчас при открытии localhost:3000
Cannot GET /

2022-10-12 15:45 UTC, closed without merging

2022-10-12 17:08 UTC, Replicatus commented on src/server.js
> +  res.status(200).sendFile(`${__dirname}/dist/index.html`);
В итоге так должно быть?
```
const express = require('express');
const fallback = require('express-history-api-fallback');
const path = require('path');
const app = express();
const PORT = 3000;
const root = path.resolve(__dirname, '../dist/');
app.use(express.static(root))
app.use(fallback('index.html', { root: root }))

app.listen(process.env.PORT || PORT, () => {});
```